# -*- coding: utf-8 -*-
"""Brute Force Detection Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpQ8CdvKe2maBJR91dFWKj-mXGP0Q0ff
"""

logins = [
    ("192.168.1.1", "fail"),
    ("192.168.1.1", "fail"),
    ("192.168.1.1", "fail"),
    ("192.168.1.2", "success")
]

attempts = {}

for ip, status in logins:
    if status == "fail":
        attempts[ip] = attempts.get(ip, 0) + 1

for ip, count in attempts.items():
    if count >= 3:
        print(f"⚠️ Possible brute force attack from {ip}")